from math import*
character_name = input("Enter your name: ")
character_age = input("Enter your age: ")
res_cAge = float(character_age)
num1 = input("Enter a number: ")
num2 = input("Enter another number: ")
result = float(num1) + float(num2)
phrase = "giraffe"
is_male = False
print("There was \n a man name " + character_name + ", ")
print("he was " + str(res_cAge) + ", ")
print("He really liked \" the " + phrase + " name " + character_name + ", ")
print("but he didn't \ like being " + str(res_cAge) + ".")
print(len(phrase))
print(phrase.upper().isupper())
print(phrase[0])
print(phrase.index("a"))
print(phrase.replace("giraffe", "Elephant"))
print(pow(int(res_cAge), 2))
print(max(int(res_cAge), 6))
print(min(int(res_cAge), 6))
print(round(int(res_cAge)))
print(floor(3.4))
print(sqrt(50))
print("Hello " + character_name + " and his age is " + character_age)
print(result)
